//Project
export const GET_PROJECTS='GET_PROJECTS'
export const GET_PROJECTS_BY_NAME='GET_PROJECTS_BY_NAME'
export const ADD_PROJECT='ADD_PROJECT'

//resource planning
export const GET_ROLE_BY_CODE='GET_ROLE_BY_CODE'
export const GET_ROLES_BY_ROLE_CODE='GET_ROLES_BY_ROLE_CODE'

//User
export const GET_CANDIDATES='GET_CANDIDATES'
export const GET_CANDIDATES_BY_NAME='GET_CANDIDATES_BY_NAME'
export const GET_CANDIDATES_BY_NAMEANDSTATUS='GET_CANDIDATES_BY_NAMEANDSTATUS'
export const GET_CANDIDATES_BY_STATUS='GET_CANDIDATES_BY_STATUS'


//extra
export const GET_LEVELS='GET_LEVELS'
export const GET_SKILLS='GET_SKILLS'
export const GET_ROLES='GET_ROLES'

//resource pool
export const GET_RESOURCEPOOL_EMP='GET_RESOURCEPOOL_EMP'
export const GET_RESOURCEPOOL_EMP_BY_RLK='GET_RESOURCEPOOL_EMP_BY_RLK'
