//Project
export const GET_PROJECTS='GET_PROJECTS'
export const GET_PROJECTS_BY_NAME='GET_PROJECTS_BY_NAME'
export const ADD_PROJECT='ADD_PROJECT'
export const GET_PROJECTS_BY_BU='GET_PROJECTS_BY_BU'
export const GET_PROJECTS_IN_BU_BY_NAME='GET_PROJECTS_IN_BU_BY_NAME'


//resource planning
export const GET_ROLE_BY_CODE='GET_ROLE_BY_CODE'
export const GET_ROLES_BY_ROLE_CODE='GET_ROLES_BY_ROLE_CODE'

//User
export const GET_CANDIDATES='GET_CANDIDATES'
export const GET_CANDIDATES_BY_NAME='GET_CANDIDATES_BY_NAME'
export const GET_CANDIDATES_BY_NAMEANDSTATUS='GET_CANDIDATES_BY_NAMEANDSTATUS'
export const GET_CANDIDATES_BY_STATUS='GET_CANDIDATES_BY_STATUS'


//extra
export const GET_LEVELS='GET_LEVELS'
export const GET_SKILLS='GET_SKILLS'
export const GET_ROLES='GET_ROLES'
export const GET_ALL_EMPS='GET_ALL_EMPS'
export const GET_ALL_EMPS_BY_BU='GET_ALL_EMPS_BY_BU'


export const GET_PNAME_BY_RLS='GET_PNAME_BY_RLS'
export const GET_PNAME_FOR_LEADER_BY_RLS='GET_PNAME_FOR_LEADER_BY_RLS'
export const GET_IDROLE_BY_CODERLS='GET_IDROLE_BY_CODERLS'
export const GET_LEADER_BY_BU='GET_LEADER_BY_BU'



//resource pool
export const GET_RESOURCEPOOL_EMP='GET_RESOURCEPOOL_EMP'
export const GET_RESOURCEPOOL_EMP_BY_RLK='GET_RESOURCEPOOL_EMP_BY_RLK'
export const GET_LEADER_BY_CODE='GET_LEADER_BY_CODE'
export const GET_RESOURCEPOOL_EMP_BY_BU='GET_RESOURCEPOOL_EMP_BY_BU'
export const GET_RESOURCEPOOL_EMP_BY_NAME='GET_RESOURCEPOOL_EMP_BY_NAME'

//request
export const GET_GENERAL_REQUEST='GET_GENERAL_REQUEST'
export const GET_GENERAL_REQUEST_BY_BU='GET_GENERAL_REQUEST_BY_BU'

export const GET_SPEC_REQUEST='GET_SPEC_REQUEST'
export const GET_SPEC_REQUEST_BY_BU='GET_SPEC_REQUEST_BY_BU'


//report
export const GET_BY_EMPLOYEE='GET_BY_EMPLOYEE'
export const GET_EMPS_BY_PNAME='GET_EMPS_BY_PNAME'


//Notification
export const GET_NOTI_BY_USERID='GET_NOTI_BY_USERID'
